version: '3.3'

services:

  console:
    image: node:15-buster
    networks:
      - p2p-network
    command: ["/bin/bash"]
    volumes:
      - ./app:/app
    working_dir: /app

  build:
    image: node:15-buster
    networks:
      - p2p-network
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      npm install
      npm build
    volumes:
      - ./app:/app
    working_dir: /app

networks:
  p2p-network: